name: Project Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.12.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Phase1 Test
        run: |
          cd phase1
          pytest -vv
          cd ..
      - name: Phase2 Test
        run: |
          cd phase2
          pytest -vv
          cd ..
      - name: Phase3 Test
        run: |
          cd phase3
          pytest -vv
          cd ..
      - name: Phase4 Test
        run: |
          cd phase4
          pytest -vv
          cd ..